// try catch block

exp = '**10/2*5'
try{
    const result = eval(exp)
    console.log(result);
}
catch{
    console.log('there is error in eval expression');
    
}
finally{
    console.log('execute in both block');
    
}



n1=20
n2=5
sum = n1+n2
console.log(sum);

